# Generated by Django 5.2 on 2025-04-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tac_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('company', models.CharField(max_length=100)),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('trainer', models.CharField(max_length=100)),
                ('approver', models.CharField(max_length=100)),
                ('enr_number', models.CharField(max_length=50, unique=True)),
                ('level_categories', models.TextField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
        ),
    ]
