# Generated by Django 5.2 on 2025-04-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorcertification',
            name='qr_code',
        ),
    ]
