# Generated by Django 5.2 on 2025-04-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_remove_operatorcertification_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorcertification',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
