# Generated by Django 5.2 on 2025-04-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_operatorcertification_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorcertification',
            name='operator',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
